README.md
The missing argument to incrementCounter prevents the example in the Readme from compiling. As a side note, the error message is rather unhelpful:
```
Warning: Error at src/Main.purs line 23, column 7 - line 24, column 5:
Error in declaration counter
Cannot unify Control.Monad.Eff.Eff with Prim.Function. Use --force to continue.
```
=> Adds a missing argument to `incrementCounter`

docs/React.md, src/React.purs
=> Parameterizing ReactThis with props and state

src/React.js
Resolves #44 
When a single element is provided as a child to the `createElement` call, `getChildren` would return a non-array element. This PR ensures that an array is returned in all cases by constructing a result array using the `React.Children` build-in functions.
=> Ensure getChildren returns an array

docs/React.md, src/React.purs
This addition is debatable, but I thought it might be handy to have these available as type synonyms.
=> Adding type synonyms for lifecycle functions

src/React/DOM/Props.js
At the moment inline styles are never rendered by purescript-react. I dont know if this has a negative effect on 
```
aria :: forall ariaAttrs. { | ariaAttrs } -> Props
aria = unsafeUnfoldProps "aria"
_data :: forall dataAttrs. { | dataAttrs } -> Props
_data = unsafeUnfoldProps "data"
```
=> fix inline styling error

docs/React.md, src/React.purs
I thought it might be handy to have a constructor that allows for passing in the `getInitialState` function. Sometimes the initial state might be derived from the props and there may not be a good plain state value that is known at the time the class is specified.
=> Adds a spec constructor function with getInitialState

docs/React.md, src/React.purs, test/Main.purs
This is a breaking change.
- Use rows instead of type constructors for read/write access types.
- Don't track the state and props types in the effects. This has proven tricky in cases with nested components in libraries like Thermite, and is unnecessary since the context tracks those types anyway.
I'll leave this here for comment for a few days before merging.
=> Simpler types

docs/React.md, src/React.js, src/React.purs
=> Create a stateless class with children

src/React.js, src/React.purs
According to React's docs:
setState() does not immediately mutate this.state but creates a
pending state transition. Accessing this.state after calling this
method can potentially return the existing value.
To make sure that transformState gets the latest value, we use
setState's callback mode.
transformState now returns Unit instead of the state type.
=> Fix transformState to use current state

src/React.js, src/React.purs
This is needed in order to implement [this](https://github.com/paf31/purescript-thermite/pull/55). `writeState` needs to call a callback for allowing async actions in `purescrtipt-thermite`.
=> Add writeState with callback

src/React.js, src/React.purs
Tested on a large-ish project.
=> Introduce preventDefault and stopPropagation. See #83.

src/React/DOM/SVG.purs
React.DOM has them, so React.DOM.SVG ought to as well.
=> Add foo' (props-free) functions for SVG elements

src/React/DOM/Props.purs
Taking an opinionated stand on https://github.com/purescript-contrib/purescript-react/issues/81 (other bindings have checked as a boolean, such as https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts).
Also adding defaultChecked as per https://facebook.github.io/react/docs/forms.html#default-value
=> adding defaultChecked property and changing checked property to take a boolean

.gitignore, package.json, src/React.js, src/React/DOM/Props.purs
The bindings now require to install `create-react-class` alongside with `react`.  This suppresses a warning in react-15.  React-16 will not allow to use `React.createClass` and it's migrating towards react classes.
=> Update for react-15

src/React.js, src/React.purs
[forceUpdate](https://facebook.github.io/react/docs/react-component.html#forceupdate). This PR includes two versions: with and without the callback argument:
```
forceUpdate :: forall eff props state. ReactThis props state -> Eff eff Unit
forceUpdateCb :: forall eff props state. ReactThis props state -> Eff eff Unit -> Eff eff Unit
```
=> Force update

README.md
There is no docs directory, link docs to Pursuit. Fix #89
=> Point documentation link to pursuit

src/React/DOM/SVG.purs
I found myself needing this recently and added it locally at the time. I thought it was worth contributing.
Info on this element is available here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
=> Add the `foreignObject` SVG element

src/React/DOM/Props.purs
This relates to #112. It adds the SVG [x](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x) and [y](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y) attributes.
I wasn't sure if I should create a `React.DOM.SVG.Props` module instead.
=> Add the SVG `x` and `y` attributes

src/React.js, src/React.purs
=> Fix event function types

src/React/DOM/Props.purs
React warns when using `selected` for `option`. They recommend to use `value` for `select`.
But when `select` is `multiple` it's impossible to pass array of values:
```purescript
value :: String -> Props
```
In latest version of React `selected` for several `option` won't work.
In JSX/JavaScript it's possible to send value as string and array:
```jsx
<select value={'A'}>
<select multiple={true} value={['B', 'C']}>
```
https://reactjs.org/docs/forms.html#the-select-tag
=> Support value property for multiselect

bower.json, package.json, src/React.js, src/React.purs, src/React/DOM/Props.purs
This removes `createClass` and `spec` as well as the dependency on
`create-react-class` in favor of `component` and `pureComponent` which
creates constructors that inherit from `React.Component` and
`React.PureComponent` in an idiomatic way for React. This also obviates
the need for some machinery like `ref` handling, which can be
implemented with `purescript-refs` instead.
=> Alternative class construction

src/React.js, src/React.purs
=> Replace ReactRender with IsReactElement

.gitignore, src/React.purs, src/React/DOM/Props.purs, src/React/SyntheticEvent.js, src/React/SyntheticEvent.purs
@natefaubion - Changes we discussed earlier in https://github.com/purescript-contrib/purescript-react/pull/140#issuecomment-381353147
=> Refactor events

bower.json, package.json, src/React.js, src/React.purs, src/React/DOM/Props.purs, src/React/SyntheticEvent.purs
Also includes some renames for consistency.
=> Updates for 0.12

src/React.purs
Some are types are not exported. For example:
```
ReactSpecAll
ReactSpecRequired
ReactSpecOptional
ReactSpecShouldComponentUpdate
GetSnapshotBeforeUpdate
ReactSpecUnsafe
ReactClassConstructor
```
They are need in other libraries (e.g. purescript-thermite) and for generic helpers.
Order of exports is changed according to appearance in code.
=> Export all types in React module

README.md, src/React.js, src/React.purs
There is some additional prose I wrote in README that should probably be reviewed to ensure it explains the concept correctly. I've also added an additional detail to the `createLeafNode` inline documentation.
There are a couple of semicolons I've added to the `React.js` foreign interface, but nothing invasive.
I've also exposed the `fragment` ReactClass in `React.purs`, for people who don't necessarily want a keyed fragment.
There were also a few typos in other parts of the inline documentation, with the troublesome double-tick ``` `` ```.
=> Better Documentation, subtle typos and syntactic details

bower.json
Verified that `pulp build` worked, though I didn't have any direct tests I can utilize handy  - I'm using purescript-react transitively.
=> bumping purescript-typelevel-prelude, fixes #168

bower.json, src/React.purs, src/React/DOM/Props.purs, src/React/Ref.js, src/React/Ref.purs
Fixes #167 by adding support for React's `createRef` API. Also distinguishes between DOM refs and React instance refs.
I've created a [branch of `purescript-react-example`](https://github.com/elliotdavies/purescript-react-example/tree/refs) to showcase the different combinations of props, callbacks and ref types (see [here](https://github.com/elliotdavies/purescript-react-example/blob/refs/src/Main.purs#L109) in particular).
----
The `ReactInstance` type probably isn't in the right place; I can move it somewhere else. (`React.purs` feels better but that causes an import cycle.)
~Otherwise the only thing I dislike is having to check `ref.current` to see whether the item is a ref, or an object with the shape `{ current: <ref> }` (see …
=> Add support for `createRef` API

README.md
The community has largely coalesced around `purescript-react-basic` as a high-level React library (as opposed to `purescript-thermite`, which saw most of its development pre-2017) and around Spago as a package manager (as opposed to Bower). This patch updates the README to point folks in the direction that is most commonly recommended on Slack, Discourse, etc.
The CSS Transition Group module has been deprecated so I removed it from the README.
=> Update related modules and installation in README

src/React.purs, src/React/Ref.purs, src/React/SyntheticEvent.purs
This allows terms of type `ReactThis props state`, `ReactClass props`, `Ref a`, `RefHandler a` and `SyntheticEvent_ event` to be coerced to type `ReactThis props' state'`, `ReactClass props'`, `Ref b`, `RefHandler b` and `SyntheticEvent_ event'` when `Coercible props props'`, `Coercible state state'`, `Coercible a b` and `Coercible event event'` hold, hence allowing the zero cost `coerce` to introduce and eliminate newtypes in components props and state, refs and their handlers and synthetic events for instance.
=> Add roles declarations to allow safe coercions

.github/workflows/ci.yml, CHANGELOG.md
**Description of the change**
This PR updates the CHANGELOG in preparation for the upcoming release of this library.
Related: purescript/purescript#3985
=> Update changelog since v8.0.0

.github/workflows/ci.yml, .gitignore, .tidyrc.json, CHANGELOG.md, src/React.purs, src/React/DOM.purs, src/React/DOM/Dynamic.purs, src/React/DOM/Props.purs, src/React/Ref.purs, src/React/SyntheticEvent.purs
**Description of the change**
Introduces the [`purs-tidy`](https://github.com/natefaubion/purescript-tidy) formatter. This formatter is a lightly opinionated tool we use to maintain a consistent style in the contrib libraries.
We ordinarily restrict to tools provided by the `core` or `contrib` projects. This tool is not, but it was developed and is maintained by core team members, and because it's a formatter it can't block maintenance or release of this library even in the event something goes catastrophically wrong with it.
---
**Checklist:**
=> Introduce purs-tidy formatter

.eslintrc.json, .github/workflows/ci.yml, CHANGELOG.md, bower.json, package.json, packages.dhall, spago.dhall, src/React.js, src/React/DOM/Props.js, src/React/Ref.js, src/React/SyntheticEvent.js, src/React/SyntheticEvent.purs
**Description of the change**
Backlinking to purescript/purescript#4244
Migrates FFI to ES modules
---
**Checklist:**
=> Update to PureScript v0.15.0

CHANGELOG.md, packages.dhall, src/React.js, src/React.purs
**Description of the change**
This updates the Monoid/Semigroup instances of `ReactElement` to represent `mempty` as `null` rather than an empty fragment, which is more in line with API expectations for third-party libraries. Due to that, this can technically be considered a breaking change? However, this change is not observable within the exported purescript-react types and interface.
---
**Checklist:**
=> Use null for mempty ReactElement
